blog/urls.py
from django.urls import path
from blog.views import * 

app_name = "blog"
urlpatterns = [
    path('',home_view , name='home_page'),
    path('about/',about_view,name='about_page'),
    path('contact/',contact_view,name='contact_page'),
    path('posts/',show_posts,name="posts"),
    path('post/<str:title>',show_post , name="post"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
] 

urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    # image
    image = models.ImageField(verbose_name="post image" , upload_to="posts/",default=None,null=True)
    # author
    author = models.ForeignKey(User,on_delete=models.SET_NULL , null=True)
    title = models.CharField(verbose_name="Title",name="title",primary_key=False,max_length=60)
    content = models.TextField(verbose_name="Content",name="content",primary_key=False)
    # tag
    # category
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now = True)
    
    
    class Meta:
        ordering = ['created_date']
        verbose_name = "پست"
        verbose_name_plural = "پست ها "
        
    def __str__(self):
        return self.title
    
    
class Contact(models.Model):
    
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['created_date']
        verbose_name = 'تماس با ما '
        verbose_name_plural = "تماس با ما ها "
    def __str__(self):
        return self.subject

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404

# Create your views here.
from blog.models import Post
def home_view(request):
    posts = Post.objects.filter(status=1)
    data = {
        'title':'Home Page',
        'posts':posts
    }
    return render(request,template_name="index.html",context=data)

def about_view(request):
    data = {
        'title':'About Page',
    }
    return render(request,template_name='about-me.html',context=data)

def contact_view(request):
    data = {
        'title':'Contact'
    }
    return render(request,template_name='contact.html',context=data)
 
def show_posts(request):
    posts = Post.objects.filter(status=1)
    return render(request,template_name="blog.html",context={"posts":posts})
def show_post(request,title):
    # data = Post.objects.filter(title=title).get()
    data = get_object_or_404(Post,title=title,status=1)
    return render(request=request,template_name="single.html",context={'data':data})

mysite/views.py
from django.http import HttpResponse,JsonResponse 
def about_us(request):
    return HttpResponse(content="About Us")

def about_us_js(request):
    return JsonResponse(data={"name":"ali"})

blog/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About-US</title>
</head>
<body>
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
    </ul>
    <h1>About US</h1>
    
</body>
</html>

templates/about-me.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content%}
    <!-- Hero Search Section Begin -->
    <div class="hero-search set-bg" data-setbg="img/search-bg.jpg">
        <div class="container">
            <div class="filter-table">
                <form action="#" class="filter-search">
                    <input type="text" placeholder="Search recipe">
                    <select id="category">
                        <option value="">Category</option>
                    </select>
                    <select id="tag">
                        <option value="">Tags</option>
                    </select>
                    <button type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
    <!-- Hero Search Section End -->

    <!-- About Me Section Begin -->
    <section class="about-me spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="about-left">
                        <img src="img/about-me.jpg" alt="">
                        <div class="about-title">
                            <span>16 January 2019</span>
                            <h2>I’m Maria Smith, <br />a mother & a food blogger</h2>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet. Donec in sodales dui, a
                                blandit nunc. Pellentesque id eros venenatis, sollicitudin neque sodales, vehicula nibh.
                                Nam massa odio, porttitor vitae efficitur non, ultricies volutpat tellus. Cras egestas
                                in lacus a finibus. Suspendisse sed urna at elit condimentum viverra. Suspendisse non
                                lobortis nisi. Maecenas accumsan quam quis porta laoreet. Aliquam felis odio, aliquet
                                fermentum semper at, porttitor ac mi. Duis vel condimentum risus. Phasellus eu dolor vel
                                neque commodo accumsan eget et enim. Pellentesque non elit sed risus tincidunt aliquam
                                eu eget metus.</p>
                            <p>Donec sit amet enim tortor. Sed egestas nulla nibh, vitae porta velit sagittis eget.
                                Donec vitae tellus semper, cursus sem id, iaculis purus. Aenean ligula risus, maximus
                                tristique eros vel, auctor ornare tortor. Aliquam vel augue sapien. Duis non auctor
                                ante, ac vestibulum tortor. Etiam quis dolor ultricies, dignissim ante a, ornare ipsum.
                                Phasellus suscipit rhoncus nulla, quis bibendum tortor elementum ac. Nullam viverra
                                tellus diam, nec accumsan orci aliquam sed. Sed placerat sagittis lacus, non rutrum diam
                                volutpat id. </p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="about-right">
                        <div class="sidebar">
                            <div class="sidebar-item">
                                <a href="#"><img src="img/cat-feature/small-1.jpg" alt=""></a>
                                <div class="sidebar-item-text">
                                    <div class="cat-name">Vegan</div>
                                    <h6>One Pot Weeknight Lasagna Soup Recipe</h6>
                                </div>
                            </div>
                            <div class="sidebar-item">
                                <a href="#"><img src="img/cat-feature/small-2.jpg" alt=""></a>
                                <div class="sidebar-item-text">
                                    <div class="cat-name">Vegan</div>
                                    <h6>Lava Cake with a Tone of Chocolate</h6>
                                </div>
                            </div>
                            <div class="sidebar-item">
                                <a href="#"><img src="img/cat-feature/small-3.jpg" alt=""></a>
                                <div class="sidebar-item-text">
                                    <div class="cat-name">Vegan</div>
                                    <h6>One Pot Weeknight Lasagna Soup Recipe</h6>
                                </div>
                            </div>
                            <div class="sidebar-item">
                                <a href="#"><img src="img/cat-feature/small-4.jpg" alt=""></a>
                                <div class="sidebar-item-text">
                                    <div class="cat-name">Vegan</div>
                                    <h6>Smoked Salmon mini Sandwiches with Onion</h6>
                                </div>
                            </div>
                            <div class="sidebar-item">
                                <a href="#"><img src="img/cat-feature/small-5.jpg" alt=""></a>
                                <div class="sidebar-item-text">
                                    <div class="cat-name">Vegan</div>
                                    <h6>Asparagus with Pork Loin and Vegetables</h6>
                                </div>
                            </div>
                            <div class="sidebar-item">
                                <a href="#"><img src="img/cat-feature/small-6.jpg" alt=""></a>
                                <div class="sidebar-item-text">
                                    <div class="cat-name">Vegan</div>
                                    <h6>Dry Cookies with Corn</h6>
                                </div>
                            </div>
                            <div class="sidebar-item">
                                <a href="#"><img src="img/cat-feature/small-7.jpg" alt=""></a>
                                <div class="sidebar-item-text">
                                    <div class="cat-name">Vegan</div>
                                    <h6>Italian Tiramisu with Coffe</h6>
                                </div>
                            </div>
                        </div>
                        <div class="about-right-add set-bg" data-setbg="img/about-right.jpg">
                            <h4>Buy my Cook Book</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- About Me Section End -->

    <!-- Similar Recipe Section Begin -->
    <section class="similar-recipe spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="img/cat-feature/small-7.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Italian Tiramisu with Coffe</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="img/cat-feature/small-6.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Dry Cookies with Corn</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="img/cat-feature/small-5.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Asparagus with Pork Loin and Vegetables</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="img/cat-feature/small-4.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Smoked Salmon mini Sandwiches with Onion</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Similar Recipe Section End -->
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Yoga Studio Template">
    <meta name="keywords" content="Yoga, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Yummy - {% block title%}{% endblock %}</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=PT+Sans:400,700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min' %}.css" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %} " type="text/css">
</head>
<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container">
            <div class="logo">
                <a href="./index.html"><img src="{% static 'img/logo.png' %}" alt=""></a>
            </div>
            <div class="nav-menu">
                <nav class="main-menu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'blog:home_page' %}">Home</a></li>
                        <li><a href="#">Pages</a>
                            <ul class="sub-menu">
                                <li><a href="{% url 'blog:about_page' %}">About Me</a></li>
                                <li><a href="categories.html">Categories</a></li>
                                <li><a href="recipe.html">Recipe</a></li>
                                <li><a href="blog.html">Blog</a></li>
                                <li><a href="contact.html">Contact</a></li>
                            </ul>
                        </li>
                        <li><a href="recipe.html">Recipes</a></li>
                        <li><a href="categories.html">Best Of</a></li>
                        <li><a href="{% url 'blog:contact_page' %}">Contact</a></li>
                    </ul>
                </nav>
                <div class="nav-right search-switch">
                    <i class="fa fa-search"></i>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    {% block content %} {% endblock %}


    
    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <div class="fs-left">
                        <div class="logo">
                            <a href="./index.html">
                                <img src="{% static 'img/footer-logo' %}.png" alt="">
                            </a>
                        </div>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                            labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo
                            viverra maecenas accumsan lacus vel facilisis.</p>
                    </div>
                </div>
                <div class="col-lg-6 offset-lg-1">
                    <form action="#" class="subscribe-form">
                        <h3>Subscribe to our newsletter</h3>
                        <input type="email" placeholder="Your e-mail">
                        <button type="submit">Subscribe</button>
                    </form>
                    <div class="social-links">
                        <a href="#"><i class="fa fa-instagram"></i><span>Instagram</span></a>
                        <a href="#"><i class="fa fa-pinterest"></i><span>Pinterest</span></a>
                        <a href="#"><i class="fa fa-facebook"></i><span>Facebook</span></a>
                        <a href="#"><i class="fa fa-twitter"></i><span>Twitter</span></a>
                        <a href="#"><i class="fa fa-youtube"></i><span>Youtube</span></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="copyright-text">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Search model -->
	<div class="search-model">
		<div class="h-100 d-flex align-items-center justify-content-center">
			<div class="search-close-switch">+</div>
			<form class="search-model-form">
				<input type="text" id="search-input" placeholder="Search here.....">
			</form>
		</div>
	</div>
	<!-- Search model end -->

    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

templates/contact.html
{% extends "base.html" %}
{% block title %}{{title}}{% endblock %}
{% block content %}
    <!-- Hero Search Section Begin -->
    <div class="hero-search set-bg" data-setbg="img/search-bg.jpg">
        <div class="container">
            <div class="filter-table">
                <form action="#" class="filter-search">
                    <input type="text" placeholder="Search recipe">
                    <select id="category">
                        <option value="">Category</option>
                    </select>
                    <select id="tag">
                        <option value="">Tags</option>
                    </select>
                    <button type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
    <!-- Hero Search Section End -->

    <!-- Contact Section Begin -->
    <section class="contact-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <form action="#" class="contact-form">
                        <h3>Leave a Comment</h3>
                        <div class="row">
                            <div class="col-lg-6">
                                <input type="text" placeholder="Your name">
                            </div>
                            <div class="col-lg-6">
                                <input type="text" placeholder="Your email">
                            </div>
                            <div class="col-lg-12">
                                <input type="text" placeholder="Subject">
                                <textarea placeholder="Comment"></textarea>
                            </div>
                        </div>
                        <button type="submit">Send Message</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact Section End -->

    <!-- Map Section Begin -->
    <div class="map">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d26440.72384129847!2d-118.24906619231132!3d34.06719475913053!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c659f50c318d%3A0xe2ffb80a9d3820ae!2sChinatown%2C%20Los%20Angeles%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1570213740685!5m2!1sen!2sbd"
            height="550" style="border:0;" allowfullscreen=""></iframe>
        <div class="map-content set-bg" data-setbg="img/map-bg.png">
            <div class="contact-addr"> col-md-6
                <span>Main Road , No 25/11</span>
                <ul>
                    <li>+34 556788 3221</li>
                    <li>contact@foodblog.com</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Map Section End -->

    <!-- Similar Recipe Section Begin -->
    <section class="similar-recipe spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="img/cat-feature/small-7.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Italian Tiramisu with Coffe</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="img/cat-feature/small-6.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Dry Cookies with Corn</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="img/cat-feature/small-5.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Asparagus with Pork Loin and Vegetables</h6>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="similar-item">
                        <a href="#"><img src="img/cat-feature/small-4.jpg" alt=""></a>
                        <div class="similar-text">
                            <div class="cat-name">Vegan</div>
                            <h6>Smoked Salmon mini Sandwiches with Onion</h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Similar Recipe Section End -->
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% block title %}{{title}}{% endblock %}
{% block content%}
    <!-- Page Top Recipe Section Begin -->
    <section class="page-top-recipe">
        <div class="container">
            <div class="row">
                {% for post in posts %}

                <div class="col-lg-6 order-lg-2">
                    <div class="pt-recipe-item large-item">
                        <div class="pt-recipe-img set-bg" data-setbg="{{post.image.url}}">
                            <i class="fa fa-plus"></i>
                        </div>
                        <div class="pt-recipe-text">
                            <span>{{ post.created_date }}</span>
                            <h3><a href="{% url 'blog:post' title=post.title %}">{{ post.title }}</a></h3>
                        </div>
                    </div>
                </div>

                {% endfor %}
                
            </div>
        </div>
    </section>
    <!-- Page Top Recipe Section End -->

    <!-- Top Recipe Section Begin -->
    <section class="top-recipe spad">
        <div class="section-title">
            <h5>Lastest</h5>
        </div>
        <div class="container po-relative">
            <div class="plus-icon">
                <i class="fa fa-plus"></i>
            </div>
            <div class="row">
                {% lastest_post %}
            </div>
        </div>
    </section>
    <!-- Top Recipe Section End -->

    <!-- Categories Filter Section Begin -->
    <div class="categories-filter-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="filter-item">
                        <ul>
                            <li class="active" data-filter="*">Vegetarian</li>
                            <li data-filter=".mostpopular">Most popular</li>
                            <li data-filter=".meatlover">Meat Lover</li>
                            <li data-filter=".glutenfree">Gluten Free</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="cf-filter" id="category-filter">
                <div class="cf-item mix all mostpopular">
                    <div class="cf-item-pic">
                        <img src="{% static 'img/cate-filter' %}/cate-filter-1.jpg" alt="">
                    </div>
                    <div class="cf-item-text">
                        <h5>Sunday Brunch: Spaghetti and Eggs Recipe</h5>
                    </div>
                </div>
                <div class="cf-item mix all mostpopular">
                    <div class="cf-item-pic">
                        <img src="{% static 'img/cate-filter' %}/cate-filter-2.jpg" alt="">
                    </div>
                    <div class="cf-item-text">
                        <h5>Sunday Brunch: Spaghetti and Eggs Recipe</h5>
                    </div>
                </div>
                <div class="cf-item mix all meatlover mostpopular">
                    <div class="cf-item-pic">
                        <img src="{% static 'img/cate-filter' %}/cate-filter-3.jpg" alt="">
                    </div>
                    <div class="cf-item-text">
                        <h5>Sunday Brunch: Spaghetti and Eggs Recipe</h5>
                    </div>
                </div>
                <div class="cf-item mix all meatlover">
                    <div class="cf-item-pic glutenfree">
                        <img src="{% static 'img/cate-filter' %}/cate-filter-4.jpg" alt="">
                    </div>
                    <div class="cf-item-text">
                        <h5>Sunday Brunch: Spaghetti and Eggs Recipe</h5>
                    </div>
                </div>
                <div class="cf-item mix all meatlover glutenfree">
                    <div class="cf-item-pic">
                        <img src="{% static 'img/cate-filter' %}/cate-filter-5.jpg" alt="">
                    </div>
                    <div class="cf-item-text">
                        <h5>Sunday Brunch: Spaghetti and Eggs Recipe</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Categories Filter Section End -->

    <!-- Feature Recipe Section Begin -->
    <section class="feature-recipe">
        <div class="section-title">
            <h5>Featured Recipes</h5>
        </div>
        <div class="container po-relative">
            <div class="plus-icon">
                <i class="fa fa-plus"></i>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    <div class="fr-item">
                        <div class="fr-item-img">
                            <img src="{% static 'img/feature-1' %}.jpg" alt="">
                        </div>
                        <div class="fr-item-text">
                            <h4>Sunday Brunch: Spaghetti and Eggs Recipe</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt
                                ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="fr-item">
                        <div class="fr-item-img">
                            <img src="{% static 'img/feature-2' %}.jpg" alt="">
                        </div>
                        <div class="fr-item-text">
                            <h4>Sunday Brunch: Spaghetti and Eggs Recipe</h4>
                            <p>Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                                aliqua. Quis ipsum suspendisse ultrices gravida.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Feature Recipe Section End -->


{% endblock %}

templates/lastest-post.html
{% load blog_tags %}
{% load static %}


{% for p  in post %}

<div class="col-lg-6">
    <div class="top-recipe-item large-item">
        <div class="top-recipe-img set-bg" data-setbg="{% static 'img/top-recipe' %}/recipe-1.jpg">
            <i class="fa fa-plus"></i>
        </div>
        <div class="top-recipe-text">
            <div class="cat-name">Desert</div>
            <a href="#">
                <h4>{{ p.title }}</h4>
            </a>
            <p>{{ p.content }} </p>
        </div>
    </div>
</div>

{% endfor %}

templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>